cdierkens/bluebird-cabinetry-and-design

- renovate.json
- web/src/Layout/Footer/Footer.js
- web/src/Layout/Head/Head.js
- web/src/Layout/Header/Header.js
- web/src/Layout/Header/Header.module.css
- web/src/Layout/Layout.css
- web/src/pages/index.js
- web/tailwind.config.js
> Integrate google fonts and add some default font styles

- studio/schemas/documents/certification.js
- studio/schemas/objects/webImage.js
- studio/schemas/schema.js
Get code from old #2 into new addWebImage Branch then master
> Add web image

- web/package.json
- web/postcss.config.js
- web/src/hooks/useWindowSize.js
- web/src/pages/index.js
- web/tailwind.config.js
> Use tailwind built in purge and render placeholder carousel 

- web/src/Layout/Head/Head.js
- web/src/Layout/Layout.js
- web/src/Layout/Layout.module.css
- web/src/Layout/__snapshots__/Layout.test.js.snap
- web/src/pages/about.js
- web/src/pages/contact.js
- web/src/pages/index.js
- web/src/pages/portfolio.js
- web/src/pages/services.js
> Add spicy placeholder pages

- web/src/Layout/Header/Header.module.css
- web/src/Layout/Header/MobileNav/MobileNav.js
- web/src/Layout/Header/MobileNav/MobileNav.module.css
- web/src/Layout/Header/MobileNav/__snapshots__/MobileNav.test.js.snap
> Tighten space in mobile nav, underline, and absolut postion logo

- web/src/Layout/Layout.js
- web/src/Layout/__snapshots__/Layout.test.js.snap
- web/src/components/PageTitle/PageTitle.js
- web/src/components/PageTitle/PageTitle.module.css
- web/src/components/PageTitle/PageTitle.test.js
- web/src/components/PageTitle/__snapshots__/PageTitle.test.js.snap
- web/src/components/PageTitle/index.js
- web/src/pages/about.js
- web/src/pages/contact.js
- web/src/pages/index.js
- web/src/pages/portfolio.js
- web/src/pages/services.js
Will need to get the background image asset and remove hard-coded bg color to close this one out
Starts #135
> Added PageTitle component and rendered them on all pages except home

- web/src/Layout/Header/Header.js
- web/src/Layout/Header/Header.module.css
> Closes #136 - highlight active page in nav

- web/src/pages/services.js
> 140 services placeholders

- web/src/components/KindWords/KindWords.js
- web/src/components/KindWords/__snapshots__/KindWords.test.js.snap
- web/src/pages/portfolio.js
Minimum viable change to make kind words a component.
We can come back to the classNames, scrolling functionality, and make it dynamic in other cards.
> Moved placeholder kind words into a component

- web/src/components/KindWords/__snapshots__/KindWords.test.js.snap
- web/src/components/Publications/Publications.js
- web/src/components/Publications/__snapshots__/Publications.test.js.snap
- web/src/icons/index.js
- web/src/pages/icons.js
- web/src/pages/portfolio.js
> 119 publications section

- web/src/Layout/Footer/Footer.js
- web/src/Layout/Footer/__snapshots__/Footer.test.js.snap
- web/src/Layout/__snapshots__/Layout.test.js.snap
closes #120 
There's still links that need to be filled in, but lets keep moving forwards and make new cards for those things to keep momentum.
> Updated footer icon to match design

- web/src/Layout/Footer/Footer.js
- web/src/Layout/Footer/__snapshots__/Footer.test.js.snap
- web/src/Layout/Header/Header.js
- web/src/Layout/Header/Header.module.css
- web/src/Layout/Header/__snapshots__/Header.test.js.snap
- web/src/Layout/Layout.css
- web/src/Layout/__snapshots__/Layout.test.js.snap
- web/src/components/Button/Button.js
- web/src/components/Button/Button.module.css
- web/src/components/Button/Button.test.js
- web/src/components/Button/__snapshots__/Button.test.js.snap
- web/src/components/Button/index.js
- web/src/components/KindWords/KindWords.js
- web/src/components/KindWords/__snapshots__/KindWords.test.js.snap
- web/src/components/LearnMore/LearnMore.js
- web/src/components/LearnMore/LearnMore.module.css
- web/src/components/LearnMore/__snapshots__/LearnMore.test.js.snap
- web/src/pages/Index.module.css
- web/src/pages/about.js
- web/src/pages/index.js
- web/src/pages/portfolio.js
- web/src/pages/services.js
> 171 button components

- web/src/pages/Index.module.css
- web/src/pages/index.js
> Use image size instead of VH for carousel container

- web/src/Layout/Footer/__snapshots__/Footer.test.js.snap
- web/src/Layout/Header/__snapshots__/Header.test.js.snap
- web/src/Layout/__snapshots__/Layout.test.js.snap
- web/src/components/Button/Button.js
- web/src/components/Button/__snapshots__/Button.test.js.snap
- web/src/components/Input/Input.js
- web/src/components/Input/Input.test.js
- web/src/components/Input/__snapshots__/Input.test.js.snap
- web/src/components/Input/index.js
- web/src/components/LearnMore/__snapshots__/LearnMore.test.js.snap
- web/src/components/PageTitle/PageTitle.module.css
- web/src/components/RadioInput/RadioInput.js
- web/src/components/RadioInput/RadioInput.test.js
- web/src/components/RadioInput/__snapshots__/RadioInput.test.js.snap
- web/src/components/RadioInput/index.js
- web/src/components/Select/Select.js
- web/src/components/Select/Select.module.css
- web/src/components/Select/Select.test.js
- web/src/components/Select/__snapshots__/Select.test.js.snap
- web/src/pages/contact.js
- web/src/pages/portfolio.js
> 142 contact page placeholders

- web/src/Layout/Footer/Footer.js
- web/src/Layout/Footer/__snapshots__/Footer.test.js.snap
- web/src/Layout/Layout.css
- web/src/Layout/__snapshots__/Layout.test.js.snap
- web/src/components/container.module.css
> Update footer links and add sr text

- web/src/components/KindWords/KindWords.js
- web/src/components/KindWords/__snapshots__/KindWords.test.js.snap
- web/tailwind.config.js
> Make kind words paginate

- web/package-lock.json
- web/package.json
- web/src/components/Input/Input.js
- web/src/components/Input/Input.test.js
- web/src/components/Input/__snapshots__/Input.test.js.snap
- web/src/components/RadioInput/RadioInput.js
- web/src/components/RadioInput/RadioInput.test.js
- web/src/components/RadioInput/__snapshots__/RadioInput.test.js.snap
- web/src/components/Select/Select.js
- web/src/components/Select/Select.module.css
- web/src/components/Select/Select.test.js
- web/src/components/Select/__snapshots__/Select.test.js.snap
- web/src/pages/contact.js
- web/src/pages/portfolio.js
> Add contact form state and validation

- web/src/components/Publications/Publications.js
- web/src/components/Publications/__snapshots__/Publications.test.js.snap
> Move text color and hover color to anchor element.

- web/functions/send-contact-email/send-contact-email.js
- web/src/components/Alert/Alert.js
- web/src/components/Alert/Alert.test.js
- web/src/components/Alert/__snapshots__/Alert.test.js.snap
- web/src/components/Alert/index.js
- web/src/components/ContactForm/ContactForm.js
- web/src/components/ContactForm/ContactForm.test.js
- web/src/components/ContactForm/__snapshots__/ContactForm.test.js.snap
- web/src/components/ContactForm/index.js
- web/src/components/Input/Input.js
- web/src/components/Input/__snapshots__/Input.test.js.snap
- web/src/components/Select/Select.module.css
- web/src/hooks/index.js
- web/src/hooks/useKeyPress.js
- web/src/pages/contact.js
> Add alerts, honeypot, and env variables for contact form

- studio/schemas/documents/portfolioImage.js
- web/__mocks__/gatsby.js
- web/src/components/PortfolioImages/PortfolioImages.js
- web/src/components/PortfolioImages/PortfolioImages.test.js
- web/src/components/PortfolioImages/__snapshots__/PortfolioImages.test.js.snap
- web/src/components/PortfolioImages/index.js
- web/src/pages/portfolio.js
> Add caption and custom styles for portfolio modal

- web/src/components/ContactForm/ContactForm.js
- web/src/components/ContactForm/__snapshots__/ContactForm.test.js.snap
> added text with link directing to the trade services page

- README.md
- web/netlify.toml
- web/src/Layout/Head/Head.js
- web/tailwind.config.js
@cdierkens 
Can you have a look? Just to make sure I didn't overlook anything. Thanks!
> minor README update and switched Sacramento font to Cookie

- web/package-lock.json
- web/src/components/PageTitle/PageTitle.module.css
- web/src/components/Publications/Publications.js
- web/src/components/Publications/__snapshots__/Publications.test.js.snap
- web/src/pages/services.js
https://github.com/cdierkens/bluebird-cabinetry-and-design/issues/326
> 326-services-page-updates

- .gitignore
- studio/.env.template
- studio/.gitignore
- studio/migrations/design-preview-to-object.js
- studio/package-lock.json
- studio/package.json
- studio/schemas/documents/designPreview.js
- studio/schemas/objects/designPreviewImage.js
- studio/schemas/schema.js
- studio/scripts/migrate.js
- flatten design preview schema and add migration
closes #743
> 743 Flatten design preview structure

- .github/workflows/pull_request_closed.yml
> 747 Remove graphql tagged endpoint on pull request closure

- studio/netlify.toml
- studio/package.json
- studio/schemas/documents/designer.js
- studio/schemas/documents/portfolioImage.js
- studio/schemas/schema.js
- web/netlify.toml
- web/package.json
- web/src/@types/block-content.d.ts
- web/src/Layout/Header/Header.module.css
- web/src/Layout/Header/Header.tsx
- web/src/Layout/Header/__snapshots__/Header.test.tsx.snap
- web/src/Layout/__snapshots__/Layout.test.tsx.snap
- web/src/components/ContactForm/ContactForm.tsx
- web/src/components/ContactForm/__snapshots__/ContactForm.test.tsx.snap
- web/src/components/PortfolioImages/ImageGrid/ImageGrid.tsx
- web/src/components/PortfolioImages/PortfolioImages.tsx
- web/src/components/PortfolioImages/PortfolioImagesContainer/PortfolioImagesContainer.tsx
- web/src/components/ToTheTradeForm/ToTheTradeForm.tsx
- web/src/components/ToTheTradeForm/__snapshots__/ToTheTradeForm.test.tsx.snap
- web/src/pages/contact.tsx
- web/src/pages/designers.tsx
- web/src/pages/trade-services.tsx
- yarn.lock
> add designers to studio

- web/src/components/PortfolioImages/AlbumImages/AlbumImages.tsx
- web/src/components/PortfolioImages/ImageGrid/ImageGrid.tsx
- web/src/components/PortfolioImages/Pagination/Pagination.tsx
- web/src/components/PortfolioImages/PortfolioImages.tsx
- web/src/components/PortfolioImages/SelectInput/SelectInput.tsx
- web/src/lib/index.ts
- web/src/lib/is-defined.ts
- web/src/pages/designers.tsx
Final replacement of all `UNSAFE_ANY` types.
> chore: finalize typescript migration

- studio/package.json
- web/package.json
- yarn.lock
Reverts cdierkens/bluebird-cabinetry-and-design#1469
> Revert "[skip netlify] Update dependency @types/react to v18"
